top_srcdir   = /usr/local/apache2/httpd-2.2.29
top_builddir = /usr/local/apache2/httpd-2.2.29
srcdir       = /usr/local/apache2/httpd-2.2.29/modules/loggers
builddir     = /usr/local/apache2/httpd-2.2.29/modules/loggers
VPATH        = /usr/local/apache2/httpd-2.2.29/modules/loggers

include $(top_srcdir)/build/special.mk

