top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/modules/arch/unix
builddir     = /usr/local/apache2/httpd-2.4.16/modules/arch/unix
VPATH        = /usr/local/apache2/httpd-2.4.16/modules/arch/unix

include $(top_srcdir)/build/special.mk

