top_srcdir   = /usr/local/apache2/httpd-2.2.29
top_builddir = /usr/local/apache2/httpd-2.2.29
srcdir       = /usr/local/apache2/httpd-2.2.29/os
builddir     = /usr/local/apache2/httpd-2.2.29/os
VPATH        = /usr/local/apache2/httpd-2.2.29/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
