top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/server/mpm/event
builddir     = /usr/local/apache2/httpd-2.4.16/server/mpm/event
VPATH        = /usr/local/apache2/httpd-2.4.16/server/mpm/event
include $(top_srcdir)/build/special.mk
