top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/modules/loggers
builddir     = /usr/local/apache2/httpd-2.4.16/modules/loggers
VPATH        = /usr/local/apache2/httpd-2.4.16/modules/loggers

include $(top_srcdir)/build/special.mk

