top_srcdir   = /usr/local/apache2/httpd-2.2.29
top_builddir = /usr/local/apache2/httpd-2.2.29
srcdir       = /usr/local/apache2/httpd-2.2.29/modules/echo
builddir     = /usr/local/apache2/httpd-2.2.29/modules/echo
VPATH        = /usr/local/apache2/httpd-2.2.29/modules/echo

include $(top_srcdir)/build/special.mk

