top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/modules/http
builddir     = /usr/local/apache2/httpd-2.4.16/modules/http
VPATH        = /usr/local/apache2/httpd-2.4.16/modules/http

include $(top_srcdir)/build/special.mk

