top_srcdir   = /usr/local/apache2/httpd-2.2.29
top_builddir = /usr/local/apache2/httpd-2.2.29
srcdir       = /usr/local/apache2/httpd-2.2.29/modules/metadata
builddir     = /usr/local/apache2/httpd-2.2.29/modules/metadata
VPATH        = /usr/local/apache2/httpd-2.2.29/modules/metadata

include $(top_srcdir)/build/special.mk

