top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/modules/cluster
builddir     = /usr/local/apache2/httpd-2.4.16/modules/cluster
VPATH        = /usr/local/apache2/httpd-2.4.16/modules/cluster
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
