top_srcdir   = /usr/local/apache2/httpd-2.2.29
top_builddir = /usr/local/apache2/httpd-2.2.29
srcdir       = /usr/local/apache2/httpd-2.2.29/server/mpm
builddir     = /usr/local/apache2/httpd-2.2.29/server/mpm
VPATH        = /usr/local/apache2/httpd-2.2.29/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
