top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/os
builddir     = /usr/local/apache2/httpd-2.4.16/os
VPATH        = /usr/local/apache2/httpd-2.4.16/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
