top_srcdir   = /usr/local/apache2/httpd-2.2.29
top_builddir = /usr/local/apache2/httpd-2.2.29
srcdir       = /usr/local/apache2/httpd-2.2.29/server/mpm/prefork
builddir     = /usr/local/apache2/httpd-2.2.29/server/mpm/prefork
VPATH        = /usr/local/apache2/httpd-2.2.29/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
