top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/modules/metadata
builddir     = /usr/local/apache2/httpd-2.4.16/modules/metadata
VPATH        = /usr/local/apache2/httpd-2.4.16/modules/metadata

include $(top_srcdir)/build/special.mk

