top_srcdir   = /usr/local/apache2/httpd-2.4.16
top_builddir = /usr/local/apache2/httpd-2.4.16
srcdir       = /usr/local/apache2/httpd-2.4.16/server/mpm
builddir     = /usr/local/apache2/httpd-2.4.16/server/mpm
VPATH        = /usr/local/apache2/httpd-2.4.16/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
